blog/urls.py
from django.urls import path

from . import views


app_name = 'blog'
urlpatterns = [
    path('', views.blog_list_view, name='post_list'),
    path('<slug>/', views.blog_detail_view, name='post_detail'),
]

personal_website/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from .views import home_view


urlpatterns = [
    path('', home_view, name='home'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('resepsionis-alvian/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('showcase-project/', include('showcase_project.urls', namespace='showcase_project')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

showcase_project/urls.py
from django.urls import path

from . import views


app_name = 'showcase_project'
urlpatterns = [
    path('', views.project_list_view, name='project_list'),
    path('<slug>/', views.project_detail_view, name='project_detail'),
]

about_me/models.py
from django.db import models


class Description(models.Model):
    short_version = models.CharField(max_length=128)
    long_version = models.TextField()


class ProfilePicture(models.Model):
    file = models.ImageField()


class PersonalInformation(models.Model):
    email = models.EmailField()
    location = models.CharField(max_length=64)
    website = models.URLField()
    linkedin = models.URLField()
    github = models.URLField()

blog/models.py
from django.db import models

from ckeditor.fields import RichTextField

from my_journey.models import TechStack


BLOG_CATEGORY_CHOICES = [
    ("OPN","Opinion"),
    ("STY","Story"),
    ("RVW","Review"),
    ("TRL","Tutorial"),
    ("EXL","Explanation"),
]

class Post(models.Model):
    title = models.CharField(max_length=256)
    summary = models.TextField()
    cover_image = models.ImageField()
    content = models.TextField()
    content_cms = RichTextField(default="")
    status = models.CharField(
        max_length=32
    )
    published_date = models.DateField()
    categoty = models.CharField(
        max_length=32, 
        choices=BLOG_CATEGORY_CHOICES, 
        default="STY"
    )
    tags = models.ManyToManyField(
        TechStack, 
        related_name='posts', 
        blank=True
    )
    slug = models.SlugField(max_length=264, default="")

    def __str__(self):
        return self.title

education/models.py
from django.db import models


class School(models.Model):
    name = models.CharField(max_length=128)
    study = models.CharField(max_length=128)
    start_date = models.DateField()
    end_date = models.DateField()
    gpa = models.FloatField(null=True)


class GpaImage(models.Model):
    school = models.ForeignKey(School, on_delete=models.CASCADE, related_name='gpa_images')
    file_image = models.ImageField()

class Thesis(models.Model):
    title = models.CharField(max_length=128)
    theme = models.CharField(max_length=128)
    url = models.URLField()
    # owner = models.ForeignKey()
    year = models.IntegerField()


class ThesisMentor(models.Model):
    thesis = models.ForeignKey(Thesis, on_delete=models.CASCADE, related_name='mentors')

"""
S1 Skripsi
- Firda summaryzation
- Dita bepy
- Dea avcweb
- Noval 
- Alvian animetachi

S2 Tesis
- Nurul Test
- Alvian monte carlo pymc

S3 Doctor
- Yuhilza neupy

"""

my_journey/models.py
from django.db import models


class Company(models.Model):
    name = models.CharField(max_length=128)
    url = models.URLField()
    field = models.CharField(max_length=64)
    about = models.CharField(max_length=128)

    def __str__(self):
        return self.name


class Accomplishment(models.Model):
    description = models.CharField(max_length=128)


class Experience(models.Model):
    role = models.CharField(max_length=64)
    description = models.CharField(max_length=128)
    start_date = models.DateField()
    end_date = models.DateField(null=True, blank=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='experiences')
    accomplishment = models.ManyToManyField(Accomplishment, related_name='experiences', blank=True)

    def __str__(self):
        return f'{self.role} - {self.company}'


class Competition(models.Model):
    description = models.CharField(max_length=128)


class Certificate(models.Model):
    image = models.ImageField()
    competition = models.ForeignKey(Competition, on_delete=models.CASCADE, related_name='certificates')


class TechStack(models.Model):
    name = models.CharField(max_length=64)
    svg = models.TextField()

    def __str__(self):
        return self.name

showcase_project/models.py
from django.db import models


class Project(models.Model):
    name = models.CharField(max_length=128)
    description = models.TextField()
    url = models.URLField()
    cover_image = models.ImageField()
    git_url = models.URLField()
    youtube_url = models.URLField()
    slug = models.SlugField(default="")
    ordering = models.IntegerField(default=0)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["ordering"]

about_me/views.py
from django.shortcuts import render

# Create your views here.

blog/views.py
from django.shortcuts import render

from .models import Post


def blog_list_view(request):
    context = {}

    blog_posts = Post.objects.filter(status='PUBLISHED')
    context['blog_posts'] = blog_posts

    return render(request, 'blog/list.html', context)


def blog_detail_view(request, slug):
    context = {}

    post = Post.objects.get(slug=slug)
    context['post'] = post

    return render(request, 'blog/detail.html', context)

education/views.py
from django.shortcuts import render

# Create your views here.

my_journey/views.py
from django.shortcuts import render

# Create your views here.

personal_website/views.py
from django.shortcuts import render

from about_me.models import Description, PersonalInformation, ProfilePicture
from blog.models import Post
from my_journey.models import Competition, Experience, TechStack
from education.models import School
from showcase_project.models import Project


def home_view(request):
    context = {}
    
    context['description'] = Description.objects.first()
    context['personal_information'] = PersonalInformation.objects.first()
    context['profile_picture'] = ProfilePicture.objects.first()

    context['experiences'] = Experience.objects.all().order_by('-start_date')
    context['competitions'] = Competition.objects.all()
    context['tech_stacks'] = TechStack.objects.all()

    context['schools'] = School.objects.all()
    
    context['blog_posts'] = Post.objects.filter(status='PUBLISHED')[:3]

    context['project_list'] = Project.objects.all()[:3]

    return render(request, 'home.html', context)

showcase_project/views.py
from django.shortcuts import render

from .models import Project


def project_list_view(request):
    context = {}

    context['project_list'] = Project.objects.all()

    return render(request, 'project/list.html', context)


def project_detail_view(request, slug):
    context = {}

    context['project'] = Project.objects.get(slug=slug)

    return render(request, 'project/detail.html', context)

templates/base_template.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="alviandk personal website">
  <meta name="author" content="alviandk">

  <title>{% block title %} {% endblock title %}</title>

  <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.png' %}"/>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet">
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  {% block custom_css %}
  
  {% endblock custom_css %}
  
</head>

<body>

  {% block content %}
  
  {% endblock content %}

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  {% block custom_js %}
  
  {% endblock custom_js %}

</body>

</html>

templates/blog/detail.html
{% extends 'base_template.html' %}
    {% load static %}

    {% block title %} Alvian DK - Blog - {{ post.title }}  {% endblock title %}

  {% block custom_css %}
  <link href="{% static 'css/custom.css' %}" rel="stylesheet">
  <link href="{% static 'css/blog.css' %}" rel="stylesheet">
  <link href="{% static 'css/skeleton-screen.css' %}" rel="stylesheet">
  {% endblock custom_css %}

  {% block content %}

  {% include 'component/navigation.html' %}

  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
        <h1 class="mt-4">{{ post.title }}</h1>
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
            <li class="breadcrumb-item"><a href="{% url 'blog:post_list' %}">Blog</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ post.title }}</li>
          </ol>
        </nav>

        <!-- Author -->
        <!-- <p class="lead">
          by
          <a href="#">Start Bootstrap</a>
        </p> -->

        <hr>

        <!-- Date/Time -->
        <p>Posted in category <a href="#">Opinion</a> on {{ post.published_date }}</p>

        <hr>

        <!-- Preview Image -->
        <div class="placeholder-item placeholder-loading">
          <img class="img-fluid rounded lazy-image" data-src="{{ post.cover_image.url }}" alt="">
        </div>
        <hr>

        <!-- Post Content -->
        {{ post.content | linebreaks }}
        <hr>

        <p>
          <b>Tags:</b> <br> 
          <span class="badge badge-pill badge-primary">Python</span>
          <span class="badge badge-pill badge-secondary">Django</span>
        </p>
        <hr>

        <!-- Comments Form -->
        <!-- <div class="card my-4">
          <h5 class="card-header">Leave a Comment:</h5>
          <div class="card-body">
            <form>
              <div class="form-group">
                <textarea class="form-control" rows="3"></textarea>
              </div>
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>
          </div>
        </div> -->

        <!-- Single Comment -->
        <!-- <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">Commenter Name</h5>
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
          </div>
        </div> -->

        <!-- Comment with nested comments -->
        <!-- <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">Commenter Name</h5>
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.

            <div class="media mt-4">
              <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
              <div class="media-body">
                <h5 class="mt-0">Commenter Name</h5>
                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
              </div>
            </div>

            <div class="media mt-4">
              <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
              <div class="media-body">
                <h5 class="mt-0">Commenter Name</h5>
                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
              </div>
            </div>

          </div>
        </div> -->

      </div>

      <!-- Sidebar Widgets Column -->
      {% include 'component/side_widget_blog.html' %}
  

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  {% include 'component/footer.html' %}
  
  {% endblock content %}

  {% block custom_js %}

    {% include 'component/lazy_image_js.html' %}

  {% endblock custom_js %}

templates/blog/list.html
{% extends 'base_template.html' %}
    {% load static %}

    {% block title %} Alvian DK - Blog {% endblock title %}

  {% block custom_css %}
  <link href="{% static 'css/custom.css' %}" rel="stylesheet">
  <link href="{% static 'css/blog.css' %}" rel="stylesheet">
  <link href="{% static 'css/skeleton-screen.css' %}" rel="stylesheet">
  {% endblock custom_css %}

  {% block content %}

  {% include 'component/navigation.html' %}

  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <!-- Blog Entries Column -->
      <div class="col-md-8">

        <h1 class="my-4">Blog</h1>

        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>  
            <li class="breadcrumb-item active" aria-current="page">Blog</li>
          </ol>
        </nav>

        {% for post in blog_posts %}  
        <!-- Blog Post -->
        <div class="card mb-4">
          <div class="placeholder-item placeholder-loading">
            <img class="card-img-top lazy-image" data-src="{{ post.cover_image.url }}" alt="Card image cap">
          </div>
          <div class="card-body">
            <h2 class="card-title">{{ post.title }}</h2>
            <p class="card-text">{{ post.summary }}</p>
            <a href="{% url 'blog:post_detail' post.slug %}" class="btn btn-info">Read More &rarr;</a>
          </div>
          <div class="card-footer text-muted">
            Posted in category <a href="#">Opinion</a> on {{ post.published_date }}
          </div>
        </div>
        {% endfor %}

        <!-- Pagination -->
        <ul class="pagination justify-content-center mb-4">
          <li class="page-item">
            <a class="page-link" href="#">&larr; Older</a>
          </li>
          <li class="page-item disabled">
            <a class="page-link" href="#">Newer &rarr;</a>
          </li>
        </ul>

      </div>

      <!-- Sidebar Widgets Column -->
      {% include 'component/side_widget_blog.html' %}

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  {% include 'component/footer.html' %}
  
  {% endblock content %}

  {% block custom_js %}

  {% include 'component/lazy_image_js.html' %}            

  {% endblock custom_js %}

templates/component/footer.html
<!-- Footer -->
<footer class="py-5 bg-green">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Alvian DK {% now "Y" %} </p>
    </div>
    <!-- /.container -->
  </footer>

templates/component/lazy_image_js.html
{% load static %}

<script type="text/javascript" src="{% static 'js/jquery.lazy.js' %}"></script>

<script type="text/javascript">
    $(function() {

        $('.lazy-image').lazy({
            bind: "event",
            delay: 700,
            afterLoad: function(element) {
                element.parent().removeClass('placeholder-loading placeholder-item');
            },
        });
        
    });

</script>

templates/component/navigation.html
{% load navigation_tag %}
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-green fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}">Alvian DK</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}#about">About
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}#experience">Journey</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}#education">Education</a>
          </li>
          <!-- <li class="nav-item {% active_css_class request.path 'blog' %}">
            <a class="nav-link" href="{% url 'blog:post_list' %}">Blog</a>
          </li> -->
          <li class="nav-item {% active_css_class request.path 'showcase-project' %}">
            <a class="nav-link" href="{% url 'showcase_project:project_list' %}">Showcase</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

templates/component/side_widget_blog.html
<div class="col-md-4">

    <!-- Search Widget -->
    <!-- <div class="card my-4">
      <h5 class="card-header">Search</h5>
      <div class="card-body">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search for...">
          <span class="input-group-append">
            <button class="btn btn-secondary" type="button">Go!</button>
          </span>
        </div>
      </div>
    </div> -->

    <!-- Categories Widget -->
    <div class="card my-4">
      <h5 class="card-header">Categories</h5>
      <div class="card-body">
        <div class="row">
          <div class="col-lg-6">
            <ul class="list-unstyled mb-0">
              <li>
                <a href="#">Opinion</a>
              </li>
              <li>
                <a href="#">Story</a>
              </li>
              <li>
                <a href="#">Review</a>
              </li>
            </ul>
          </div>
          <div class="col-lg-6">
            <ul class="list-unstyled mb-0">
              <li>
                <a href="#">Tutorial</a>
              </li>
              <li>
                <a href="#">Explanation</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <!-- Side Widget -->
    <div class="card my-4">
      <h5 class="card-header">Tags</h5>
      <div class="card-body">
        <span class="badge badge-pill badge-primary">Python</span>
        <span class="badge badge-pill badge-secondary">Django</span>
        <span class="badge badge-pill badge-success">Javascript</span>
        <span class="badge badge-pill badge-danger">Java</span>
        <span class="badge badge-pill badge-warning">Golang</span>
        <span class="badge badge-pill badge-info">Angular</span>
        <span class="badge badge-pill badge-dark">Docker</span>
        <span class="badge badge-pill badge-success">Soft Skill</span>
      </div>
    </div>

  </div>

templates/project/detail.html
{% extends 'base_template.html' %}
    {% load static %}

    {% block title %} Alvian DK - Project - {{ project.name }} {% endblock title %}

  {% block custom_css %}
  <link href="{% static 'css/custom.css' %}" rel="stylesheet">
  <link href="{% static 'css/showcase-project.css' %}" rel="stylesheet">
  <link href="{% static 'css/showcase-detail.css' %}" rel="stylesheet">
  <link href="{% static 'css/skeleton-screen.css' %}" rel="stylesheet">
  {% endblock custom_css %}

  {% block content %}
  {% include 'component/navigation.html' %}

  <header class="bg-info text-white">
    <div class="container text-center">
      <h1 class="text-white">Showcase Project</h1>
      <h2 class="text-white">"{{ project.name }}"</h2>
      <div class="social-icons">
        <a href="{{ project.git_url }}">
          <i class="fab fa-git-square"></i>
        </a>
        <!-- <a href="{{ project.url }}">
          <i class="fab fa-wpexplorer"></i>
        </a>
        <a href="{{ project.youtube_url }}">
          <i class="fab fa-youtube"></i>
        </a> -->
      </div>
    </div>
  </header>

  <section class="projects-section bg-light" id="projects">
    <div class="container">
      <div class="mb-5">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb my-4">
            <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>            
            <li class="breadcrumb-item" aria-current="page"><a href="{% url 'showcase_project:project_list' %}">Showcase Project</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{ project.name }}</li>
          </ol>
        </nav>
      </div>
      <div class="row align-items-center no-gutters mb-4 mb-lg-5">
        <div class="col-xl-6 col-lg-6">
          <div class="placeholder-item placeholder-loading">
            <img class="img-fluid mb-3 mb-lg-0 lazy-image" data-src="{{ project.cover_image.url }}" alt="">
          </div>
        </div>
        <div class="col-xl-6 col-lg-6">
            <div class="featured-text text-left text-lg-left">
                <h2>Description</h2>
                <p class="text-black-50 mb-0">
                  {{ project.description | linebreaks }}
                </p>
            </div>
        </div>
        
      </div>
    </div>
  </section>

  <!-- <section id="services">
    <div class="container">
      <div class="row">
        <div class="col-lg-8">
          <h2>Tech Stacks</h2>
          <ul class="list-inline dev-icons-lg mb-3">
            <li class="list-inline-item mb-3" data-toggle="tooltip" data-placement="top" title="" data-original-title="Python">
              <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" focusable="false" width="1.01em" height="1em" style="-ms-transform: rotate(360deg); -webkit-transform: rotate(360deg); transform: rotate(360deg);" preserveAspectRatio="xMidYMid meet" viewBox="0 0 256 255"><defs><linearGradient x1="12.959%" y1="12.039%" x2="79.639%" y2="78.201%" id="IconifyId-173a9e39fee-6e9748-8"><stop stop-color="#387EB8" offset="0%"></stop><stop stop-color="#366994" offset="100%"></stop></linearGradient><linearGradient x1="19.128%" y1="20.579%" x2="90.742%" y2="88.429%" id="IconifyId-173a9e39fee-6e9748-9"><stop stop-color="#FFE052" offset="0%"></stop><stop stop-color="#FFC331" offset="100%"></stop></linearGradient></defs><path d="M126.916.072c-64.832 0-60.784 28.115-60.784 28.115l.072 29.128h61.868v8.745H41.631S.145 61.355.145 126.77c0 65.417 36.21 63.097 36.21 63.097h21.61v-30.356s-1.165-36.21 35.632-36.21h61.362s34.475.557 34.475-33.319V33.97S194.67.072 126.916.072zM92.802 19.66a11.12 11.12 0 0 1 11.13 11.13a11.12 11.12 0 0 1-11.13 11.13a11.12 11.12 0 0 1-11.13-11.13a11.12 11.12 0 0 1 11.13-11.13z" fill="url(#IconifyId-173a9e39fee-6e9748-8)"></path><path d="M128.757 254.126c64.832 0 60.784-28.115 60.784-28.115l-.072-29.127H127.6v-8.745h86.441s41.486 4.705 41.486-60.712c0-65.416-36.21-63.096-36.21-63.096h-21.61v30.355s1.165 36.21-35.632 36.21h-61.362s-34.475-.557-34.475 33.32v56.013s-5.235 33.897 62.518 33.897zm34.114-19.586a11.12 11.12 0 0 1-11.13-11.13a11.12 11.12 0 0 1 11.13-11.131a11.12 11.12 0 0 1 11.13 11.13a11.12 11.12 0 0 1-11.13 11.13z" fill="url(#IconifyId-173a9e39fee-6e9748-9)"></path></svg>    
            </li>
            <li class="list-inline-item mb-3" data-toggle="tooltip" data-placement="top" title="" data-original-title="Django">
                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" focusable="false" width="0.79em" height="1em" style="-ms-transform: rotate(360deg); -webkit-transform: rotate(360deg); transform: rotate(360deg);" preserveAspectRatio="xMidYMid meet" viewBox="0 0 256 326">
                <g fill="#2BA977">
                  <path d="M114.784 0h53.278v244.191c-27.29 5.162-47.38 7.193-69.117 7.193C33.873 251.316 0 222.245 0 166.412c0-53.795 35.93-88.708 91.608-88.708c8.64 0 15.222.68 23.176 2.717V0zm1.867 124.427c-6.24-2.038-11.382-2.717-17.965-2.717c-26.947 0-42.512 16.437-42.512 45.243c0 28.046 14.88 43.532 42.17 43.532c5.896 0 10.696-.332 18.307-1.351v-84.707z"></path>
                  <path d="M255.187 84.26v122.263c0 42.105-3.154 62.353-12.411 79.81c-8.64 16.783-20.022 27.366-43.541 39.055l-49.438-23.297c23.519-10.93 34.901-20.588 42.17-35.327c7.61-15.072 10.01-32.529 10.01-78.445V84.261h53.21z"></path>
                  <path d="M196.608 0h53.278v54.135h-53.278V0z"></path></g>
              </svg>    
            </li>
          </ul>  
        </div>
      </div>
    </div>
  </section> -->

  

  <!-- <section id="contact" class="bg-light">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 mx-auto">
          <h2>Preview</h2>
           <div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/zpOULjyy-n8?rel=0" allowfullscreen></iframe>
          </div>
        </div>
      </div>
    </div>
  </section> -->

  {% include 'component/footer.html' %}


  {% endblock content %}

  {% block custom_js %}

    {% include 'component/lazy_image_js.html' %}

    <script type="text/javascript">
      $(function() {
  
        $('[data-toggle="tooltip"]').tooltip();

     });
  
    
    </script>

  {% endblock custom_js %}

templates/project/list.html
{% extends 'base_template.html' %}
    {% load static %}

    {% block title %} Alvian DK - Showcase Project {% endblock title %}

  {% block custom_css %}
  <link href="{% static 'css/custom.css' %}" rel="stylesheet">
  <link href="{% static 'css/showcase-project.css' %}" rel="stylesheet">
  <link href="{% static 'css/skeleton-screen.css' %}" rel="stylesheet">
  {% endblock custom_css %}

  {% block content %}
  {% include 'component/navigation.html' %}

  <!-- Page Content -->
  <main role="main">

    <header class="bg-info text-white">
      <div class="container text-center">
        <h1 class="text-white">Showcase Project</h1>
        <p class="lead text-white">
          Software development craft, tools, and process. <br> The art of make things done.
        </p>
      </div>
    </header>
  
    <section id="about">
      <div class="container">
        <div class="mb-5">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Showcase Project</li>
            </ol>
          </nav>
        </div>
        <div class="row">
          {% for project in project_list %}
          <div class="col-md-4 mb-5">
            <div class="card h-100">
              <div class="placeholder-item placeholder-loading">
                <img class="card-img-top lazy-image" data-src="{{ project.cover_image.url }}" alt="">
              </div>
              <div class="card-body">
                <h4 class="card-title">{{ project.name }}</h4>
                <p class="card-text">{{ project.description | truncatewords:20 }}</p>
              </div>
              <div class="card-footer">
                <a href="{% url 'showcase_project:project_detail' project.slug %}" class="btn btn-info">Find Out More!</a>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </section>

  
  
  </main>

  {% include 'component/footer.html' %}
  
  {% endblock content %}
  {% block custom_js %}

  {% include 'component/lazy_image_js.html' %}
            

  {% endblock custom_js %}